name: Playwright with FastAPI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # -------------------------
    # Setup Python & FastAPI
    # -------------------------
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install FastAPI dependencies
      run: |
        cd backend
        pip install -r requirements.txt

    - name: Start FastAPI server
      run: |
        cd backend
        nohup uvicorn main:app --host 127.0.0.1 --port 8000 &
        sleep 5   # wait for server to start

    # -------------------------
    # Setup Node & Playwright
    # -------------------------
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    # -------------------------
    # Run Playwright tests
    # -------------------------
    - name: Run Playwright tests
      run: npx playwright test

    # -------------------------
    # Upload Playwright report
    # -------------------------
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
